name: Reply with search results

on:
  issues:
    types: [opened]

jobs:
  auto-reply-and-search:
    runs-on: ubuntu-latest
    steps:
      - name: Reply with greeting message
        uses: actions/github-script@v4
        with:
          script: |
            const greeting = `Hello @${context.payload.issue.user.login},\n\nThank you for submitting an issue. We appreciate your interest in our project! \n\nI will now try to find an answer to your question.`
            return github.issues.createComment({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: greeting
            })
          github-token: ${{ secrets.GOOGLE_TOKEN }}
          
      # - name: Get search results
      #   uses: actions/http-request@v1
      #   with:
      #     url: 'https://api.serpstack.com/search'
      #     method: 'GET'
      #     querystring: |
      #       access_key: ${{ secrets.SERPSTACK_ACCESS_KEY }}
      #       query: ${{ github.event.issue.title }}
      #       num: 5
      #       output: json
      #   id: search-results
      #   continue-on-error: true
      - name: Get chat response
        uses: actions/http-request@v1
        with:
          url: 'https://api.openai.com/v1/engine/davinci-codex/completions'
          method: 'POST'
          headers: |
            Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}
            Content-Type: application/json
          body: |
            {
              "prompt": "${{ github.event.issue.title }}",
              "temperature": 0.7,
              "max_tokens": 60,
              "top_p": 1,
              "frequency_penalty": 0,
              "presence_penalty": 0
            }
        id: chat-response

      - name: Reply with chat response
        run: |
          CHAT_RESPONSE=$(echo "$(<${{ steps.chat-response.outputs.body }})" | jq -r '.choices[0].text')
          echo "$CHAT_RESPONSE"
          curl -s -H "Authorization: token ${{ secrets.GOOGLE_TOKEN }}" -X POST -d "{\"body\": \"$CHAT_RESPONSE\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
        if: ${{ success() }}

      - name: Get search results
        run: |
          query=$(echo "${{ github.event.issue.title }}" | python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read().strip()))")
          echo "https://serpapi.com/search?q=${query}&num=5&engine=google"
          curl -s "https://serpapi.com/search?q=${query}&num=5&engine=google&api_key=${{ secrets.SERPSTACK_ACCESS_KEY }}" > search_results.json
        id: search-results

      - name: Reply with search results
        run: |
          SEARCH_RESULTS=$(cat search_results.json)
          echo "$SEARCH_RESULTS"
          RESULTS_COUNT=$(echo "$SEARCH_RESULTS" | jq '.organic_results | length')
          REPLY="Here are the top ${RESULTS_COUNT} results from Google:\n"
          for ((i=0; i<$RESULTS_COUNT; i++)); do
            TITLE=$(echo "$SEARCH_RESULTS" | jq -r ".organic_results[$i].title")
            URL=$(echo "$SEARCH_RESULTS" | jq -r ".organic_results[$i].link")
            REPLY="${REPLY}• [${TITLE}](${URL})\n"
          done
          REPLY=$(echo "$REPLY" | sed 's/"/\\"/g')
          echo $REPLY
          curl -s -H "Authorization: token ${{ secrets.GOOGLE_TOKEN }}" -X POST -d "{\"body\": \"$REPLY\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"

        if: ${{ success() }}

      # - name: Reply with google url
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       const query = context.payload.issue.title
      #       const url = `https://www.google.com/search?q=${encodeURIComponent(query)}`
      #       const reply = `I found some information that may be helpful. You can check it out here: ${url}`
      #       return github.issues.createComment({
      #         issue_number: context.payload.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: reply
      #       })
      #     github-token: ${{ secrets.GOOGLE_TOKEN }}