name: Auto Reply and Search

on:
  issues:
    types: [opened]

jobs:
  auto-reply-and-search:
    runs-on: ubuntu-latest
    steps:
      # - name: Get search results
      #   uses: actions/http-request@v1
      #   with:
      #     url: 'https://api.serpstack.com/search'
      #     method: 'GET'
      #     querystring: |
      #       access_key: ${{ secrets.SERPSTACK_ACCESS_KEY }}
      #       query: ${{ github.event.issue.title }}
      #       num: 5
      #       output: json
      #   id: search-results
      #   continue-on-error: true

      - name: Get search results
        run: |
          query=$(echo ${{ github.event.issue.title }} | python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read().strip()))")
          curl -s "https://serpapi.com/search?q=${query}&num=5&engine=google&api_key=${{ secrets.SERPSTACK_ACCESS_KEY }}" > search_results.json
        id: search-results

      - name: Reply with search results
        run: |
          SEARCH_RESULTS=$(cat search_results.json)
          RESULTS_COUNT=$(echo "$SEARCH_RESULTS" | jq '.organic_results | length')
          REPLY="Here are the top ${RESULTS_COUNT} results from Google:\n\n"
          for ((i=0; i<$RESULTS_COUNT; i++)); do
            TITLE=$(echo "$SEARCH_RESULTS" | jq -r ".organic_results[$i].title")
            URL=$(echo "$SEARCH_RESULTS" | jq -r ".organic_results[$i].url")
            REPLY="${REPLY}• [${TITLE}](${URL})\n"
          done
          curl -s -H "Authorization: token ${{ secrets.GOOGLE_TOKEN }}" -X POST -d "{\"body\": \"$REPLY\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"

        if: ${{ success() }}
